---

sudo: required

language: cpp

services:
  - docker

env:
  matrix:
    - MESOS_VERSION=1.4.1-2.0.1
    - MESOS_VERSION=1.3.2-2.0.1
    - MESOS_VERSION=1.2.3-2.0.1

script:
  - docker build --build-arg MESOS_VERSION=${MESOS_VERSION} .
