---

sudo: required

language: cpp

services:
  - docker

env:
  matrix:
    - MESOS_VERSION=1.5.0-2.0.1 DEBIAN_VERSION=stretch
    - MESOS_VERSION=1.4.1-2.0.1 DEBIAN_VERSION=stretch

script:
  - docker build --build-arg MESOS_VERSION=${MESOS_VERSION} --build-arg DEBIAN_VERSION=${DEBIAN_VERSION} .
